### ISSUE TITLE
need releases on github for software update to work

### ISSUE THREAD

**Issue by jneilliii** [moof-src/ArduCamFocus#12]
In order for the Software Update hook to function properly you must add releases in github that match the version number identified in the setup.py. So if you merge my PR, something like this for the next stable release.

![image](https://user-images.githubusercontent.com/5249455/115951845-ee0d9900-a4b0-11eb-8ff7-33c1d8b90ff0.png)

Then if you create a new branch named `rc` in your repo and push testing changes to it, when you do the release like the below (important parts highlighted) anyone with Release Candidate enabled for the plugin in Software Update settings will get an update notice.

![image](https://user-images.githubusercontent.com/5249455/115951933-607e7900-a4b1-11eb-9eed-998ca013e451.png)

**Comment by moof-src** [comment]
I put in my own try except before I saw yours.  See if my 0.0.6 update
works for you.
