### ISSUE TITLE
"Unable to use SMBus/I2C

### ISSUE THREAD

**Issue by ultimase** [moof-src/ArduCamFocus#2]
Hello,
I do apologize in advance, I am very much a newbie with it comes to raspberry pi's and Linux. 

I purchased this camera with the hope that I could utilize it in Octoprint to focus on the actual bed and object being worked on. 
Jneilliii, and others have been extremely helpful in pointing me in the right direction (https://community.octoprint.org/t/arducam-auto-focus-camera/21511/10), but I've run into this fault and I've not been able to find much about it.

I'm sure it's probably something very simple, but again, very very very new to this stuff.

Thank you.

**Comment by RoachCoach521** [comment]
Wanted to echo the above. 

Followed these instructions: https://www.raspberrypi.org/forums/viewtopic.php?t=250596

```
git clone https://github.com/ArduCAM/RaspberryPi.git
cd RaspberryPi/Motorized_Focus_Camera
chmod +x enable_i2c_vc.sh
./enable_i2c_vc.sh
sudo reboot
```

The camera is visible, and the proper line is in the config.txt

But every time I go to use the plugin I get _unable to use SMBus/I2C_

figure I'm missing something dumb

Thanks!

**Comment by moof-src** [comment]
I observed the same problem.   I am testing a fix and will post updated documentation tomorrow if everything works.

**Comment by Polly-Jeanius** [comment]
Ditto, same SMBus/I2C issue here. Thanks heaps for looking into a fix @moof-src. Will check back tomorrow - fingers crossed.

**Comment by jneilliii** [comment]
It's probably something simple like
```
sudo apt update
sudo apt upgrade
```

**Comment by Polly-Jeanius** [comment]
> It's probably something simple like
> 
> ```
> sudo apt update
> sudo apt upgrade
> ```

Unfortunately not :( Already running latest on Buster. Did all the updates/upgrades before installing the plugin.

**Comment by moof-src** [comment]
I left updated installation instructions.  After following my new instructions, I was able to get the ArduCamFocus plugin to work on a Raspberry Pi 4B using octopi 0.17.0.  I also updated the plugin with one minor enhancement.

**Comment by moof-src** [comment]
Please look at README.md for new installation requirements.  I left the following instructions:

This plugin uses I2C to communicate with the camera.  That is not enabled by default.  The ArduCamFocus plugin will not function until
you enable I2C.
  ssh to your octopi and enter this commands (this only needs to be done once):
```bash
if ! grep -Fxq "^#ArduCamFocus$" /boot/config.txt; then
sudo cat << end_of_file > /boot/config.txt
#ArduCamFocus
dtparam=i2c_vc=on
dtparam=i2c_arm=on
end_of_file
fi
```
After executing the above command, the file /boot/config.txt should now have the commands to enable I2C.  In addition, you have to enable the I2C
kernel module using raspi-config.  Again, ssh to your octopi, and then enter this command:
```bash
sudo raspi-config
```

1. select "5 Interfacing Options"
2. select "P5 I2C"
3. raspi-config will ask, "Would you like the ARM I2C interface to be enabled?"
4. select "Yes"
5. you should see, "The ARM I2C interface is enabled"
6. select "Finish"

After you reboot, the camera should become operational in OctoPrint.

**Comment by RoachCoach521** [comment]
Just wanted to say thanks, this worked perfectly for me. 

The plugin works with no errors and the camera is now controllable.

**Comment by dudeway4** [comment]
I am getting the error -bash: /boot/config.txt: Permission denied



> ```shell
> if ! grep -Fxq "^#ArduCamFocus$" /boot/config.txt; then
> sudo cat << end_of_file > /boot/config.txt
> #ArduCamFocus
> dtparam=i2c_vc=on
> dtparam=i2c_arm=on
> end_of_file
> fi
> ```

**Comment by altcoin725** [comment]
> I am getting the error -bash: /boot/config.txt: Permission denied
> 
> > ```shell
> > if ! grep -Fxq "^#ArduCamFocus$" /boot/config.txt; then
> > sudo cat << end_of_file > /boot/config.txt
> > #ArduCamFocus
> > dtparam=i2c_vc=on
> > dtparam=i2c_arm=on
> > end_of_file
> > fi
> > ```

I get the same permission denied error.

**Comment by moof-src** [comment]
cooy and paste the whole script at once.  do not type it in or copy line by
line.

**Comment by grilparto** [comment]
Also getting permission denied pasting the script in.  Had to do a sudo su to be able to do this for some reason.

**Comment by pawrequest** [comment]
arducam was working but focus wasn't - i got the same `unable to use SMBus/I2C` error as above when trying to focus, so i followed above instructions and now the camera doesn't work at all - `webcam stream not loaded`...

any ideas? thanks!
