### ISSUE TITLE
I2C adding access denied

### ISSUE THREAD

**Issue by TimTamShortage** [moof-src/ArduCamFocus#4]
I am trying to add an arducam to my octopi setup and I'm having a confusing issue and don't know how to proceed.

I am entering the 

if ! grep -Fxq "^#ArduCamFocus$" /boot/config.txt; then
sudo cat << end_of_file >> /boot/config.txt
#ArduCamFocus
dtparam=i2c_vc=on
dtparam=i2c_arm=on
end_of_file
fi

set of commands to set up the camera and all I'm getting back is:

-bash: /boot/config.txt: Permission denied

I know this will be some stupid, simple issue but I'm sshing into my pi as user "pi" with my password, but don't see why it's not working. If you can point me in a direction that can help me proceed with this, I would be very grateful. Thank you for creating this!

**Comment by moof-src** [comment]
The commands must be entered exactly and preferably all at once.  the
commands you copied in the email were double spaced, but shouldn’t be.  the
second line has the command “sudo” which raises the privilege level for the
rest of the script.  Sudo prompts for the root password.  If you don’t
enter the password properly or you don’t have permission to run the sudo
command then it will fail.

All this script does is at these lines to the end of /boot/config.txt.

#ArduCamFocus
dtparam=i2c_vc=on
dtparam=i2c_arm=on

you can edit /boot/config.txt with a text editor and add the lines manually
if they aren’t already in the file.  you must edit the file as root or you
won’t be able to save it.

**Comment by TimTamShortage** [comment]
That's what I had guessed it was doing, I tried editing the config file manually before, let me try it again and see. 
Thank you!

**Comment by TimTamShortage** [comment]
Okay so it appears I was having a problem with the cable I was using, which figures.
Glad I could get some advice though
