### ISSUE TITLE
Octoprint Plugin Manager installing non Python 3 version

### ISSUE THREAD

**Issue by ccanevit** [moof-src/ArduCamFocus#5]
I upgraded to python 3, and I noticed that the plugin manager keeps installing the version that does not support python 3.
I've uninstalled it, and reinstalled via the plugin manager, but still getting the issue.

Name | Actions
-- | --
ArduCamFocus (0.0.4)  Homepage  moofChange pi camera Focus AGPLv3  Python >=2.7,<3

**Comment by moof-src** [comment]
fixed syntax error.  install 0.0.5
